# Generated by Django 4.1.7 on 2023-04-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complete', 'complete'), ('Active', 'active'), ('Inactive', 'inactive')], default='active', max_length=20),
        ),
    ]
