# Generated by Django 4.1.7 on 2023-04-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Complete', 'complete'), ('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=20, null=True),
        ),
    ]
