# Generated by Django 4.1.7 on 2023-06-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelMarketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltrainingconfig',
            name='loss',
            field=models.CharField(blank=True, choices=[('mae', 'Mean Absolute Error'), ('mse', 'Mean Squared Error'), ('rmse', 'Root Mean Squared Error'), ('binary_crossentropy', 'Binary Cross-Entropy'), ('categorical_crossentropy', 'Categorical Cross-Entropy')], max_length=128, null=True),
        ),
    ]
